// <auto-generated />
using System;
using Barter.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barter.Infrastructure.Migrations
{
    [DbContext(typeof(BarterDbContext))]
    partial class BarterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Barter.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74892eba-ae27-467b-8f4b-5060b46fd76c"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("da221366-a4ad-45d0-a6ab-9716bd4e8625"),
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("Barter.Domain.Models.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExchangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemOfferedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemRequestedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("Barter.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e036fa2-6532-4e20-92f8-fcf0265f49f2"),
                            CategoryId = new Guid("74892eba-ae27-467b-8f4b-5060b46fd76c"),
                            Condition = 0,
                            Description = "This is an example item.",
                            ImageUrl = "image1.jpg",
                            ItemType = 0,
                            Name = "Electronic Item",
                            OwnerId = new Guid("363e30bc-5062-47ea-a3a7-ac50fb85b5a0"),
                            Views = 10
                        },
                        new
                        {
                            Id = new Guid("9def0b9a-4bf7-4f58-87b4-317357f164e6"),
                            CategoryId = new Guid("da221366-a4ad-45d0-a6ab-9716bd4e8625"),
                            Condition = 1,
                            Description = "This is an example item.",
                            ImageUrl = "image2.jpg",
                            ItemType = 1,
                            Name = "Clothing Item",
                            OwnerId = new Guid("adc71544-77af-4102-ad2b-45e6a6bef40d"),
                            Views = 20
                        });
                });

            modelBuilder.Entity("Barter.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MobileNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("363e30bc-5062-47ea-a3a7-ac50fb85b5a0"),
                            Address = "Address1",
                            Email = "user1@example.com",
                            MobileNumber = 1234567890L,
                            Password = "password1",
                            ProfilePicture = "profile1.jpg",
                            Username = "Vaja"
                        },
                        new
                        {
                            Id = new Guid("adc71544-77af-4102-ad2b-45e6a6bef40d"),
                            Address = "Address2",
                            Email = "user2@example.com",
                            MobileNumber = 9876543210L,
                            Password = "password2",
                            ProfilePicture = "profile2.jpg",
                            Username = "Goga"
                        });
                });

            modelBuilder.Entity("Barter.Domain.Models.Category", b =>
                {
                    b.HasOne("Barter.Domain.Models.Category", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Barter.Domain.Models.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
